project:
  type: book
  output-dir: docs

book:
  title: "An Introduction to Probability"
  subtitle: "With Applications to Computational Finance using R"
  author: "Martin Summer"
  date: last-modified
  date-format: D MMMM, YYYY
  site-url: https://martin-summer-1090.github.io/Probability_Introduction/
  chapters:
     - index.qmd
     - 01-lecture1.qmd
     - 02-lecture2.qmd
     - 03-lecture3.qmd
     - 04-lecture4.qmd
     - 05-lecture5.qmd
     - 06-references.qmd  # Ensure this file exists and is formatted correctly
     - 07-appendix.qmd

bibliography: references.bib
citeproc: true  # Ensures proper citation processing

format:
  html:
    theme: cosmo
    code-fold: false
    tbl-cap-location: bottom
    reference-location: margin  # Moves all references to the margin
    

appendix: true
